# Generated by Django 3.2.9 on 2021-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='game',
        ),
        migrations.AddField(
            model_name='bet',
            name='away_team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
