# Generated by Django 3.2.9 on 2021-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook_app', '0002_auto_20211215_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_choice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
