# Generated by Django 3.2.9 on 2021-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook_app', '0003_auto_20211216_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='sports_book',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
