# Generated by Django 3.2.9 on 2021-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook_app', '0004_bet_sports_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(blank=True, choices=[('h2h', 'h2h'), ('spreads', 'spreads'), ('totals', 'totals')], max_length=255, null=True),
        ),
    ]
