# Generated by Django 3.2.9 on 2021-12-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook_app', '0006_alter_bet_sports_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='sports_book',
            field=models.CharField(blank=True, choices=[('William Hill (US)', 'William Hill (US)'), ('FOX Bet', 'FOX Bet'), ('FanDuel', 'FanDuel')], max_length=255, null=True),
        ),
    ]
